### PR TITLE
Button: fix unstyled button :hover and :active styles

### PR DESCRIPTION
**Pull request by Benaiah**
Followup to #63.

## Proposed changes

- Adds explicit background and foreground color settings to `.usa-button.usa-button--unstyled`.

### CODE REVIEW

**Review by LouisFettet — COMMENTED** [review]
I think that the `outline` and `outline-inverse` variants are still affecting the button when it's `unstyled`, which I assume is not intentional.

**Comment by Benaiah** [comment]
> I think that the `outline` and `outline-inverse` variants are still affecting the button when it's `unstyled`, which I assume is not intentional.

That's what I thought too, but the [USWDS code sample for the Button component](https://designsystem.digital.gov/components/button/) actually shows that the `usa-button--unstyled` class is supposed to work on _all_ the button variants.

**Comment by LouisFettet** [comment]
This is what I'm seeing in storybook (similar for `outline-inverse` and when it's disabled):
Screenshot 2023-04-27 at 12 31 40 PM

Whereas in the USWDS docs the unstyled button with the "outline" variant doesn't show that border.

**Comment by Benaiah** [comment]
Oh, my bad! I thought I'd already fixed that. Should be fixed now, and I've also fixed the color of the unstyled inverse button.

**Comment by LouisFettet** [comment]
Sorry, a couple more combinations I'm seeing with oddities:
1. `text-only` variant that's `disabled` has contrast issues with hover and active states:
Screenshot 2023-04-27 at 1 10 17 PM

2. `outline` and `outline-inverse` variants that are `disabled` _sometimes_ have some sizing issues on hover and active states:

Kapture 2023-04-27 at 14 07 11

**Comment by Benaiah** [comment]
@LouisFettet I've rebased this and (I _think_) fixed all the style issues with every permutation of `variant`, `disabled`, and `unstyled`. Thanks for the thorough review! It's ready for another look now.

**Review by LouisFettet — APPROVED** [review]
Looks great! Thanks for dealing with all my comments. After we merge this and #50 we'll want to do some follow-up work to standardize how we're handling colors.

**Pull request merged**
